import React from "react";
import _ from "lodash";
import { Button, CountdownTimer, CustomHeader, Footer } from "components";
// import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

const Dashboard = () => {
  
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
    <head>
      <title>UGLY HOLIDAY</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
    <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <h1 className="font-burtons text-xl">Ugly Holiday</h1>
          <ul className="flex items-center">
            <li>
            </li>
          </ul>
        </nav>
        <div className="text-center p-10 py-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Waiting The Beast
          </h2>
          <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            <CountdownTimer/>
          </h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            STAY WILD
          </p>
        </div>
      </section>
    </main>
  </div>
  );
};

export default Dashboard;
